# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development: &dev
  min_messages: WARNING
  adapter: postgresql
  encoding: utf8
  template: template0
  username: rails
  password: SuperSecretPassword
  database: statuspage_test
  pool: 5
  timeout: 5000

production:
  <<: *dev
  database: statuspage_production
  pool: 30

staging:
  <<: *dev
  database: statuspage_staging
  pool: 30
