#!/bin/bash

if [ -z $ENVIRONMENT ]; then ENVIRONMENT=staging; fi

/usr/bin/bundler install --binstubs /app/bin --path /app/tmp/bundle --without development test --deployment
/usr/bin/bundler exec unicorn -c /app/config/unicorn/$ENVIRONMENT.rb -E $ENVIRONMENT -D
